### ISSUE TITLE
Work on prototyping each screens on figma

### ISSUE THREAD

**Issue by Theverifiedvee** [zuri-training/proj_fetch_meta_data_team_83#39]
Web view Prototyping done and completed

**Comment by Dvrmvc** [comment]
I worked on prototyping the Mobile View of the Website (HIFI) screens so that users can seamlessly get a live view of the website via Mobile View. [View here](https://www.figma.com/file/zdA5Fl8wrHI2wBe1e3lR7j/ZURI-TASK-CONTRIBUTION?node-id=744%3A8409)
