### ISSUE TITLE
Design the landing page with figma for the front end team

### ISSUE THREAD

**Issue by Idimmusix** [zuri-training/proj_fetch_meta_data_team_83#7]
Design the lofi, so that the front end team can start working immediately.

**Comment by Theverifiedvee** [comment]
This task has been completed

**Comment by Dvrmvc** [comment]
Work Done. [View here](https://www.figma.com/file/zdA5Fl8wrHI2wBe1e3lR7j/FIGMA?node-id=744%3A8409)
