### ISSUE TITLE
Design: Create a lofi page where the user can upload their profile picture.

### ISSUE THREAD

**Issue by Idimmusix** [zuri-training/proj_fetch_meta_data_team_83#9]
Create the page where the user will be able to upload their profile picture and change their personal informations like first name, last name, uusername and email address.
Also create the error page/popup, that comes up if the user's profile picture size is larger than our max_upload_size or if the user uploads a file that is not an image type

**Comment by Dvrmvc** [comment]
I'm done designing the lo-fi and Hi-fi of the profile picture page where they can change their personal information like username and email address. And also worked on the error page popup as requested
